// The four things that can happen to a Project in this slice, as plain data.
//
// A command is a *request*, not a change: it says what the caller wants and carries everything
// the reducer needs to do it. Two consequences follow from that, and they are the reason this file
// exists separately from `apply.ts`.
//
// **Every id and every timestamp is in the command.** Nothing here is generated by the reducer,
// because a reducer that mints an id or reads a clock is no longer a function of its input, and
// undo, replay and tests all depend on it being one (contracts/model-api.md, Principle IV). The
// caller — `apps/editor` today, a server later — owns `crypto.randomUUID()` and `new Date()`.
//
// **Link status is not here.** Whether a Source is Linked or Offline is derived at runtime from
// the device-local link table and a permission grant (data-model.md); it is not in the Project
// document, so no command can set it and no undo can toggle it. `relink-source` is in this list
// because a Relink leaves something behind *in the document* — which file the Source now names —
// and that part, like every other document change, has to be undoable. The handle itself is the
// link table's business and never reaches the reducer.

import type { Clip, PixelSize, Source, SourceFingerprint } from "../document/types"
import type { Timebase } from "../timebase"

/** What every command carries. */
interface CommandFields {
  /**
   * The instant the caller stamps on this edit, as an ISO 8601 string — it becomes the Project's
   * `modifiedAt`. It is a field rather than a `Date.now()` inside the reducer so that applying the
   * same command twice gives the same document, which is what makes the reducer testable and its
   * patches replayable.
   */
  readonly at: string
}

/**
 * Brings a Project into being. Applied to no Project at all (`null`), so its inverse is simply
 * "there is no Project again".
 *
 * It carries the first Track, because this slice has exactly one video Track (data-model.md) and
 * there is no `add-track` command to make one — so the Track is born with the Project, and its id
 * comes from the caller like every other id.
 */
export interface CreateProjectCommand extends CommandFields {
  readonly type: "create-project"
  readonly projectId: string
  readonly name: string
  readonly timebase: Timebase
  readonly frameSize: PixelSize
  readonly track: { readonly id: string; readonly name: string }
}

/**
 * Records media the user brought in. The `Source` arrives whole, already read by the engine
 * (`source-attached`): its duration and Source Timebase are exact ratios in the Source's own
 * timescale and the reducer never renumbers them into Frames (Principle II's exception).
 *
 * A Source is immutable once imported and its id is never reused, so importing the same file twice
 * makes a second Source rather than changing the first.
 */
export interface ImportSourceCommand extends CommandFields {
  readonly type: "import-source"
  readonly source: Source
}

/** Places part of a Source onto a Track at a whole Frame, where no other Clip already is. */
export interface AddClipCommand extends CommandFields {
  readonly type: "add-clip"
  readonly trackId: string
  readonly clip: Clip
}

/**
 * Records that an Offline Source has been pointed at the bytes it lost.
 *
 * Only the document's half of a Relink is here: the name the Source now goes by and the
 * fingerprint a future Relink will check against. Binding the handle, verifying it against the
 * old fingerprint and moving the Source from Offline to Linked all happen outside the document
 * (ADR 0005, FR-021), which is precisely why undoing this cannot take a Source Offline again.
 */
export interface RelinkSourceCommand extends CommandFields {
  readonly type: "relink-source"
  readonly sourceId: string
  readonly name: string
  readonly fingerprint: SourceFingerprint
}

/** Everything that can change a Project in this slice. */
export type Command =
  CreateProjectCommand | ImportSourceCommand | AddClipCommand | RelinkSourceCommand
